language: csharp
sudo: required  
dist: trusty  
mono: latest
dotnet: 2.2.203
env:
  global:
    - ResolveNuGetPackageAssets=true
    - EnableNuGetPackageRestore=true
os:
  - linux
  - osx
solution: Afonsoft.Extensions.sln
install:
  - dotnet restore
script:
  - dotnet build